### ISSUE TITLE
Undocumented authentication parameter: client ID

### ISSUE THREAD

**Issue by etanol** [txerpa/txapi-documentation#1]
The _authentication_ endpoint `/v1/auth` requires a `client_id` as part of the URL path.  However, documentation doesn't show examples of valid client IDs nor explains how to obtain one.

And, without authentication, the rest of the API cannot be used.

**Comment by sandrabg86** [comment]
Hi,
This is the old documentation in the follow link you have the new: https://api.txerpa.com/api/v1/doc/
Sorry for the inconvenience

**Comment by etanol** [comment]
Thanks, it works now.  I obtained the client ID via customer service.

Resolving.
